<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=H(T('账号开通申请'))?></h4>
            </div>
            <div class="modal-body" style="padding: 20px;">
                <img src="/ajax/gapper/auth/tust/qrcode" class="pull-right" width="120" height="120" />
                <div>
                    <label class="control-label"><?=H(T('学院名称'))?>:</label>
                    <span><?=H($department) ?: '--'?></span>
                </div>
                <div>
                    <label class="control-label"><?=H(T('课题组名称'))?>:</label>
                    <span><?=H($group) ?: '--'?></span>
                </div>
                <div>
                    <label class="control-label"><?=H(T('PI 姓名'))?>:</label>
                    <span><?=H($name) ?: '--'?></span>
                </div>
                <div>
                    <label class="control-label"><?=H(T('PI 工号'))?>:</label>
                    <span><?=H($wid) ?: '--'?></span>
                </div>
                <div>
                    <label class="control-label"><?=H(T('PI 邮箱'))?>:</label>
                    <span><?=H($email) ?: '--'?></span>
                </div>
                <div>
                    <label class="control-label"><?=H(T('联系电话'))?>:</label>
                    <span><?=H($phone) ?: '--'?></span>
                </div>
                <div>
                    <label class="control-label"><?=H(T('地址'))?>:</label>
                    <span><?=H($address) ?: '--'?></span>
                </div>
            </div>
            <div class="modal-footer"><form class="gapper-auth-form" action="ajax/gapper/auth/tust/edit-info">
                <input type="submit" class="btn btn-default" value="<?=H(T('修改'))?>" />
                <a target="_blank" href="/ajax/gapper/auth/tust/pdf?_r=<?=H(rand(1, 1000))?>" class="btn btn-primary"><?=H(T('确认, 去打印'))?></a>
            </form></div>
        </div>
    </div>
</div>

