<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=H(T('账号开通申请'))?></h4>
            </div>
            <form class="modal-body form gapper-auth-form" method="POST" action="ajax/gapper/auth/tust/register">
                <div class="row">
                    <div class="form-group col-xs-6<?=isset($error['department']) ? ' has-error' : ''?>">
                        <label class="control-label"><?=H(T('学院名称'))?></label>
                        <input class="form-control" type="text" name="department" value="<?=$department ? H($department) : ''?>" />
                        <?php if (isset($error['department'])) { ?>
                        <div class="text-danger text-right"><small><?=H($error['department'])?></small></div>
                        <?php } ?>
                    </div>
                    <div class="form-group col-xs-6<?=isset($error['group']) ? ' has-error' : ''?>">
                        <label class="control-label"><?=H(T('课题组名称'))?></label>
                        <input class="form-control" type="text" name="group" value="<?=$group ? H($group) : ''?>" />
                        <?php if (isset($error['group'])) { ?>
                        <div class="text-danger text-right"><small><?=H($error['group'])?></small></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-xs-6<?=isset($error['name']) ? ' has-error' : ''?>">
                        <label class="control-label"><?=H(T('PI 姓名'))?></label>
                        <input class="form-control" type="text" name="name" value="<?=$name ? H($name) : ''?>" />
                        <?php if (isset($error['name'])) { ?>
                        <div class="text-danger text-right"><small><?=H($error['name'])?></small></div>
                        <?php } ?>
                    </div>
                    <div class="form-group col-xs-6<?=isset($error['wid']) ? ' has-error' : ''?>">
                        <label class="control-label"><?=H(T('PI 工号'))?></label>
                        <input class="form-control" type="text" name="wid" value="<?=$wid ? H($wid) : ''?>" />
                        <?php if (isset($error['wid'])) { ?>
                        <div class="text-danger text-right"><small><?=H($error['wid'])?></small></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-xs-6<?=isset($error['email']) ? ' has-error' : ''?>">
                        <label class="control-label"><?=H(T('PI 邮箱'))?><small class="text-muted">(<?=H(T('邮箱用于登录，一经添加不能修改'))?>)</small></label>
                        <input class="form-control" type="text" name="email" value="<?=$email ? H($email) : ''?>" />
                        <?php if (isset($error['email'])) { ?>
                        <div class="text-danger text-right"><small><?=H($error['email'])?></small></div>
                        <?php } ?>
                    </div>
                    <div class="form-group col-xs-6"<?=isset($error['phone']) ? ' has-error' : ''?>>
                        <label class="control-label"><?=H(T('联系电话'))?></label>
                        <input class="form-control" type="text" name="phone" value="<?=$phone ? H($phone) : ''?>" />
                        <?php if (isset($error['phone'])) { ?>
                        <div class="text-danger text-right"><small><?=H($error['phone'])?></small></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group"<?=isset($error['address']) ? ' has-error' : ''?>>
                    <label class="control-label"><?=H(T('地址'))?></label>
                    <input class="form-control" type="text" name="address" value="<?=$address ? H($address) : ''?>" />
                        <?php if (isset($error['address'])) { ?>
                        <div class="text-danger text-right"><small><?=H($error['address'])?></small></div>
                        <?php } ?>
                </div>
                <div class="form-group">
                    <input class="form-control btn btn-primary" type="submit" value="<?=H(T('提交'))?>"/>
                </div>
            </form>
        </div>
    </div>
</div>

